### ISSUE TITLE
Publish to Maven Central?

### ISSUE THREAD

**Issue by Sindisil** [tomlj/tomlj#26]
With bintray going away on May 1, is there any chance of publishing tomlj to Maven Central?

**Comment by cleishm** [comment]
Sure. Feel free to submit a PR to modify the publish phase in gradle to do so.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
This depends on which provider you want to use. I used [Sonatype OSSRH](https://central.sonatype.org/publish/publish-guide/) (because it was the easiest way) for my fork, see [here](https://github.com/xtomlj/xtomlj/commit/7a55bb37408d1989b257c30723d859ade30d6b8e) and [here](https://github.com/xtomlj/xtomlj/commit/5b7d9f84364b459f07fb1f43aaa2cccc9af4bbb2).
Someone would have to create an account and repository there though.

I can also provide the 2 commits as a pull request as those are the only changes required to publish to OSSRH.

**Comment by cleishm** [comment]
I requested the Sonatype repository here: https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-85325?filter=allopenissues

It would be great if you want to provide the PRs to match that.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
It looks to me like tomlj has already been [released](https://search.maven.org/artifact/org.tomlj/tomlj/1.0.0/pom) in version 1.0.0 in Maven Central or am I missing something?

However, #52 is still needed to publish artifacts there.

**Comment by cleishm** [comment]
@kPYKx7Ddw4n1aIKZ Yes - it was sync'd from the bintray repo. It was a long time ago so I forgot there was an OSSRH project already (https://issues.sonatype.org/browse/OSSRH-48548). I'll merge #52 and we can release there directly.

**Comment by cleishm** [comment]
@kPYKx7Ddw4n1aIKZ I believe everything is ready for a new 1.1.0 release. Do you want to review and confirm? I'll plan to release it later today.

**Comment by cleishm** [comment]
I think I spoke too soon - I'm fighting with gradle/maven and it seems there is still an issue. It wouldn't publish without adding `tasks.publishDistributionPublicationToMavenRepository { dependsOn project.tasks.signArchives }`, but now regular builds fail with `The following model rules could not be applied due to unbound inputs and/or subjects` 🤷‍♂️

**Comment by cleishm** [comment]
Ignore the above - fixed by c9769e3

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
@cleishm After #49 has been merged, I think everything is fine now. 👍
